// Zepp OS Watchface generated by Amazfit Watchface Editor ©Strike76
// Generated on Mon Mar 23 13:38:03 GMT+02:00 2026
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('ZeppWatchfaceEditor');

        // ****************************************************
        // Variabili globali
        // ****************************************************
        // Sensori condivisi
        let shared_weather_sensor = null;

        let cityTextWidget_widget_normal_19 = null;

        let cityTextWidget_widget_aod_9 = null;
        // ****************************************************
        // Dichiarazioni variabili widget
        // ****************************************************
        let widget_normal_1 = '';
        let widget_normal_2 = '';
        let widget_normal_3 = '';
        let widget_normal_4 = '';
        let widget_normal_5 = '';
        let widget_normal_6 = '';
        let widget_normal_7 = '';
        let widget_normal_8 = '';
        let widget_normal_9 = '';
        let widget_normal_10 = '';
        let widget_normal_11 = '';
        let widget_normal_12 = '';
        let widget_normal_13 = '';
        let widget_normal_14 = '';
        let widget_normal_15 = '';
        let widget_normal_16 = '';
        let widget_normal_17 = '';
        let widget_normal_18 = '';
        let widget_normal_19 = '';
        let widget_normal_20 = '';
        let widget_normal_21 = '';
        let widget_normal_22 = '';
        let widget_normal_23 = '';
        let widget_normal_24 = '';
        let widget_normal_25 = '';
        let widget_normal_26 = '';
        let widget_aod_1 = '';
        let widget_aod_2 = '';
        let widget_aod_3 = '';
        let widget_aod_4 = '';
        let widget_aod_5 = '';
        let widget_aod_6 = '';
        let widget_aod_7 = '';
        let widget_aod_8 = '';
        let widget_aod_9 = '';
        // ****************************************************


        // ****************************************************
        // Funzioni helper
        // ****************************************************
        function updateCityName_widget_normal_19() {
          if (!cityTextWidget_widget_normal_19 || !shared_weather_sensor) return;
          try {
            const weatherData = shared_weather_sensor.getForecastWeather();
            if (weatherData && weatherData.cityName) {
              cityTextWidget_widget_normal_19.setProperty(hmUI.prop.TEXT, weatherData.cityName);
            }
          } catch (e) {
            // Ignora errori sensore
          }
        }

        function updateCityName_widget_aod_9() {
          if (!cityTextWidget_widget_aod_9 || !shared_weather_sensor) return;
          try {
            const weatherData = shared_weather_sensor.getForecastWeather();
            if (weatherData && weatherData.cityName) {
              cityTextWidget_widget_aod_9.setProperty(hmUI.prop.TEXT, weatherData.cityName);
            }
          } catch (e) {
            // Ignora errori sensore
          }
        }
        // ****************************************************

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // ========== NORMAL MODE WIDGETS ==========

                  // Inizializzazione sensori condivisi
                  shared_weather_sensor = hmSensor.createSensor(hmSensor.id.WEATHER);

                // "Normal" Background Widget
                widget_normal_1 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 0,
                  y: 0,
                  w: 480,
                  h: 480,
                  src: 'background_ed15585c.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Combined Time Widget (Normal)
                widget_normal_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                  hour_zero: 1,
                  hour_startX: 25,
                  hour_startY: 220,
                  hour_array: ['chars_332F8A64_000.png','chars_332F8A64_001.png','chars_332F8A64_002.png','chars_332F8A64_003.png','chars_332F8A64_004.png','chars_332F8A64_005.png','chars_332F8A64_006.png','chars_332F8A64_007.png','chars_332F8A64_008.png','chars_332F8A64_009.png'],
                  hour_align: hmUI.align.LEFT,
                  minute_zero: 1,
                  minute_startX: 95,
                  minute_startY: 220,
                  minute_array: ['chars_332F8A64_000.png','chars_332F8A64_001.png','chars_332F8A64_002.png','chars_332F8A64_003.png','chars_332F8A64_004.png','chars_332F8A64_005.png','chars_332F8A64_006.png','chars_332F8A64_007.png','chars_332F8A64_008.png','chars_332F8A64_009.png'],
                  minute_align: hmUI.align.LEFT,
                  minute_follow: 0,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_4 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 85,
                  y: 200,
                  src: 'chars_7B253F5D_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday Widget "Normal"
                widget_normal_5 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                  x: 33,
                  y: 198,
                  week_en: ["chars_7FACE2F4_000.png","chars_7FACE2F4_001.png","chars_7FACE2F4_002.png","chars_7FACE2F4_003.png","chars_7FACE2F4_004.png","chars_7FACE2F4_005.png","chars_7FACE2F4_006.png"],
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Day Widget "Normal"
                widget_normal_6 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                  day_startX: 92,
                  day_startY: 198,
                  day_sc_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_tc_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_en_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_zero: 1,
                  day_space: 0,
                  day_align: hmUI.align.LEFT,
                  day_is_character: false,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Month Widget "Normal"
                widget_normal_7 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                  month_startX: 105,
                  month_startY: 198,
                  month_sc_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_tc_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_en_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_zero: 0,
                  month_space: 0,
                  month_is_character: true,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // "Normal" Mode - Icon Widget
                widget_normal_8 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 189,
                  y: 98,
                  w: 33,
                  h: 57,
                  src: 'batt_1_33x57_h135s21b101.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_9 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 222,
                  y: 115,
                  src: 'chars_BA062315_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Previsioni meteo Widget "Normal"
                widget_normal_10 = hmUI.createWidget(hmUI.widget.IMG_LEVEL, {
                  x: 136,
                  y: 153,
                  image_array: ["set_7_35x35_h0s20b114_meteo_1.png", "set_7_35x35_h0s20b114_meteo_2.png", "set_7_35x35_h0s20b114_meteo_3.png", "set_7_35x35_h0s20b114_meteo_4.png", "set_7_35x35_h0s20b114_meteo_5.png", "set_7_35x35_h0s20b114_meteo_6.png", "set_7_35x35_h0s20b114_meteo_7.png", "set_7_35x35_h0s20b114_meteo_8.png", "set_7_35x35_h0s20b114_meteo_9.png", "set_7_35x35_h0s20b114_meteo_10.png", "set_7_35x35_h0s20b114_meteo_11.png", "set_7_35x35_h0s20b114_meteo_12.png", "set_7_35x35_h0s20b114_meteo_13.png", "set_7_35x35_h0s20b114_meteo_14.png", "set_7_35x35_h0s20b114_meteo_15.png", "set_7_35x35_h0s20b114_meteo_16.png", "set_7_35x35_h0s20b114_meteo_17.png", "set_7_35x35_h0s20b114_meteo_18.png", "set_7_35x35_h0s20b114_meteo_19.png", "set_7_35x35_h0s20b114_meteo_20.png", "set_7_35x35_h0s20b114_meteo_21.png", "set_7_35x35_h0s20b114_meteo_22.png", "set_7_35x35_h0s20b114_meteo_23.png", "set_7_35x35_h0s20b114_meteo_24.png", "set_7_35x35_h0s20b114_meteo_25.png", "set_7_35x35_h0s20b114_meteo_26.png", "set_7_35x35_h0s20b114_meteo_27.png", "set_7_35x35_h0s20b114_meteo_28.png", "set_7_35x35_h0s20b114_meteo_29.png"],
                  image_length: 29,
                  type: hmUI.data_type.WEATHER_CURRENT,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // "Normal" Mode - Icon Widget
                widget_normal_11 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 225,
                  y: 176,
                  w: 20,
                  h: 20,
                  src: 'heart_4_20x20_h108s16b123.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_12 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 254,
                  y: 170,
                  src: 'chars_1F05B716_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // "Normal" Mode - Icon Widget
                widget_normal_13 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 241,
                  y: 223,
                  w: 29,
                  h: 30,
                  src: 'step_12_29x30.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_14 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 283,
                  y: 222,
                  src: 'chars_998AAC0_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // "Normal" Mode - Icon Widget
                widget_normal_15 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 226,
                  y: 280,
                  w: 25,
                  h: 25,
                  src: 'arc_25x25_h114s26b120.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_16 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 259,
                  y: 276,
                  src: 'chars_4C06DF7A_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // "Normal" Mode - Icon Widget
                widget_normal_17 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 197,
                  y: 331,
                  w: 35,
                  h: 35,
                  src: 'custom_icon_1774225907045_35x35_h39s17b200.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Text Widget "Normal"
                widget_normal_18 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 238,
                  y: 333,
                  src: 'chars_D8A663C4_000.png',
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                  // City Widget Normal
                  cityTextWidget_widget_normal_19 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: 34,
                    y: 143,
                    w: 102,
                    h: 60,
                    text_size: 20,
                    char_space: 0,
                    color: 0xFFFFFFFF,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '',
                    show_level: hmUI.show_level.ONLY_NORMAL
                  });
                  updateCityName_widget_normal_19();

                // "Normal" Mode - Status Widget
                widget_normal_20 = hmUI.createWidget(hmUI.widget.IMG_STATUS, {
                  x: 225,
                  y: 430,
                  src: 'bluetooth_5_b_30x30.png',
                  type: hmUI.system_status.DISCONNECT,
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_21 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 196,
                  y: 111,
                  w: 100,
                  h: 35,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'Settings_batteryManagerScreen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_22 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 219,
                  y: 170,
                  w: 142,
                  h: 35,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'heart_app_Screen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_23 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 219,
                  y: 275,
                  w: 151,
                  h: 35,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'BioChargeHomeScreen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_24 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 240,
                  y: 220,
                  w: 109,
                  h: 35,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'activityAppScreen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_25 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 191,
                  y: 332,
                  w: 117,
                  h: 35,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'StressHomeScreen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Click Widget "Normal"
                widget_normal_26 = hmUI.createWidget(hmUI.widget.BUTTON, {
                  x: 120,
                  y: 139,
                  w: 63,
                  h: 60,
                  text: '',
                press_src: 'trasparente.png',
                normal_src: 'trasparente.png',
                click_func: () => {
                hmApp.startApp({ url: 'WeatherScreen', native: true })
                			  },
                  show_level: hmUI.show_level.ONLY_NORMAL
                });                // ========== AOD MODE WIDGETS ==========

                // "AOD" Background Widget
                widget_aod_1 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 0,
                  y: 0,
                  w: 480,
                  h: 480,
                  src: 'background_9a5c016a.png',
                  alpha: 255,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Combined Time Widget (AOD)
                widget_aod_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                  hour_zero: 1,
                  hour_startX: 25,
                  hour_startY: 220,
                  hour_array: ['chars_332F8A64_000.png','chars_332F8A64_001.png','chars_332F8A64_002.png','chars_332F8A64_003.png','chars_332F8A64_004.png','chars_332F8A64_005.png','chars_332F8A64_006.png','chars_332F8A64_007.png','chars_332F8A64_008.png','chars_332F8A64_009.png'],
                  hour_align: hmUI.align.LEFT,
                  minute_zero: 1,
                  minute_startX: 95,
                  minute_startY: 220,
                  minute_array: ['chars_332F8A64_000.png','chars_332F8A64_001.png','chars_332F8A64_002.png','chars_332F8A64_003.png','chars_332F8A64_004.png','chars_332F8A64_005.png','chars_332F8A64_006.png','chars_332F8A64_007.png','chars_332F8A64_008.png','chars_332F8A64_009.png'],
                  minute_align: hmUI.align.LEFT,
                  minute_follow: 0,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Weekday Widget "AOD"
                widget_aod_4 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                  x: 33,
                  y: 198,
                  week_en: ["chars_7FACE2F4_000.png","chars_7FACE2F4_001.png","chars_7FACE2F4_002.png","chars_7FACE2F4_003.png","chars_7FACE2F4_004.png","chars_7FACE2F4_005.png","chars_7FACE2F4_006.png"],
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Text Widget "AOD"
                widget_aod_5 = hmUI.createWidget(hmUI.widget.IMG, {
                  x: 85,
                  y: 200,
                  src: 'chars_320AB2EE_000.png',
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Day Widget "AOD"
                widget_aod_6 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                  day_startX: 92,
                  day_startY: 198,
                  day_sc_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_tc_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_en_array: ["chars_1AF2A253_000.png","chars_1AF2A253_001.png","chars_1AF2A253_002.png","chars_1AF2A253_003.png","chars_1AF2A253_004.png","chars_1AF2A253_005.png","chars_1AF2A253_006.png","chars_1AF2A253_007.png","chars_1AF2A253_008.png","chars_1AF2A253_009.png"],
                  day_zero: 1,
                  day_space: 0,
                  day_align: hmUI.align.LEFT,
                  day_is_character: false,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Month Widget "AOD"
                widget_aod_7 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                  month_startX: 105,
                  month_startY: 198,
                  month_sc_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_tc_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_en_array: ["chars_C0323A9C_000.png","chars_C0323A9C_001.png","chars_C0323A9C_002.png","chars_C0323A9C_003.png","chars_C0323A9C_004.png","chars_C0323A9C_005.png","chars_C0323A9C_006.png","chars_C0323A9C_007.png","chars_C0323A9C_008.png","chars_C0323A9C_009.png","chars_C0323A9C_010.png","chars_C0323A9C_011.png"],
                  month_zero: 0,
                  month_space: 0,
                  month_is_character: true,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                // Previsioni meteo Widget "AOD"
                widget_aod_8 = hmUI.createWidget(hmUI.widget.IMG_LEVEL, {
                  x: 136,
                  y: 153,
                  image_array: ["set_7_35x35_h0s20b114_meteo_1.png", "set_7_35x35_h0s20b114_meteo_2.png", "set_7_35x35_h0s20b114_meteo_3.png", "set_7_35x35_h0s20b114_meteo_4.png", "set_7_35x35_h0s20b114_meteo_5.png", "set_7_35x35_h0s20b114_meteo_6.png", "set_7_35x35_h0s20b114_meteo_7.png", "set_7_35x35_h0s20b114_meteo_8.png", "set_7_35x35_h0s20b114_meteo_9.png", "set_7_35x35_h0s20b114_meteo_10.png", "set_7_35x35_h0s20b114_meteo_11.png", "set_7_35x35_h0s20b114_meteo_12.png", "set_7_35x35_h0s20b114_meteo_13.png", "set_7_35x35_h0s20b114_meteo_14.png", "set_7_35x35_h0s20b114_meteo_15.png", "set_7_35x35_h0s20b114_meteo_16.png", "set_7_35x35_h0s20b114_meteo_17.png", "set_7_35x35_h0s20b114_meteo_18.png", "set_7_35x35_h0s20b114_meteo_19.png", "set_7_35x35_h0s20b114_meteo_20.png", "set_7_35x35_h0s20b114_meteo_21.png", "set_7_35x35_h0s20b114_meteo_22.png", "set_7_35x35_h0s20b114_meteo_23.png", "set_7_35x35_h0s20b114_meteo_24.png", "set_7_35x35_h0s20b114_meteo_25.png", "set_7_35x35_h0s20b114_meteo_26.png", "set_7_35x35_h0s20b114_meteo_27.png", "set_7_35x35_h0s20b114_meteo_28.png", "set_7_35x35_h0s20b114_meteo_29.png"],
                  image_length: 29,
                  type: hmUI.data_type.WEATHER_CURRENT,
                  show_level: hmUI.show_level.ONLY_AOD
                });
                  // City Widget AOD
                  cityTextWidget_widget_aod_9 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: 34,
                    y: 143,
                    w: 200,
                    h: 60,
                    text_size: 20,
                    char_space: 0,
                    color: 0xFFFFFFFF,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '',
                    show_level: hmUI.show_level.ONLY_AOD
                  });
                  updateCityName_widget_aod_9();
                // Widget delegate per gestire resume/pause
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                              // City Widget Normal
                              updateCityName_widget_normal_19();                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                              // City Widget AOD
                              updateCityName_widget_aod_9();                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}
