// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // Time Display - IMG_TIME Widget
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 25,
                    hour_startY: 220,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 95,
                    minute_startY: 220,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 92,
                    day_startY: 198,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday - IMG_WEEK Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 33,
                    y: 198,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Arc - ARC_PROGRESS Widget
                let widget_5 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 130,
                    radius: 70,
                    start_angle: -90,
                    end_angle: 270,
                    color: 0x00CC88,
                    line_width: 8,
                    type: hmUI.data_type.BATTERY,
                    level: 50,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Value - TEXT_IMG Widget
                let widget_6 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 215,
                    y: 118,
                    w: 50,
                    h: 25,
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Rate Value - TEXT_IMG Widget
                let widget_7 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 150,
                    y: 350,
                    w: 80,
                    h: 30,
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Steps Value - TEXT_IMG Widget
                let widget_8 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 300,
                    y: 350,
                    w: 80,
                    h: 30,
                    font_array: ['step_digit_0.png', 'step_digit_1.png', 'step_digit_2.png', 'step_digit_3.png', 'step_digit_4.png', 'step_digit_5.png', 'step_digit_6.png', 'step_digit_7.png', 'step_digit_8.png', 'step_digit_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Activity Arc - ARC_PROGRESS Widget
                let widget_9 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 380,
                    radius: 50,
                    start_angle: -120,
                    end_angle: 120,
                    color: 0xFF6B6B,
                    line_width: 6,
                    type: hmUI.data_type.STEP,
                    level: 50,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Bluetooth Status - IMG_STATUS Widget
                let widget_10 = hmUI.createWidget(hmUI.widget.IMG_STATUS, {
                    x: 225,
                    y: 420,
                    src: 'bluetooth_30x30.png',
                    type: hmUI.system_status.DISCONNECT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Shortcut - BUTTON Widget
                let widget_11 = hmUI.createWidget(hmUI.widget.BUTTON, {
                    x: 190,
                    y: 60,
                    w: 100,
                    h: 100,
                    text: '',
                    press_src: 'trasparente.png',
                    normal_src: 'trasparente.png',
                    click_func: () => {
                hmApp.startApp({ url: 'Settings_batteryManagerScreen', native: true })
                              },
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Shortcut - BUTTON Widget
                let widget_12 = hmUI.createWidget(hmUI.widget.BUTTON, {
                    x: 120,
                    y: 320,
                    w: 90,
                    h: 90,
                    text: '',
                    press_src: 'trasparente.png',
                    normal_src: 'trasparente.png',
                    click_func: () => {
                hmApp.startApp({ url: 'heart_app_Screen', native: true })
                              },
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Activity Shortcut - BUTTON Widget
                let widget_13 = hmUI.createWidget(hmUI.widget.BUTTON, {
                    x: 270,
                    y: 320,
                    w: 90,
                    h: 90,
                    text: '',
                    press_src: 'trasparente.png',
                    normal_src: 'trasparente.png',
                    click_func: () => {
                hmApp.startApp({ url: 'activityAppScreen', native: true })
                              },
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // City Name - TEXT Widget
                let widget_14 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: 170,
                    y: 445,
                    w: 140,
                    h: 25,
                    text_size: 18,
                    char_space: 0,
                    color: 0xCCCCCCFF,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '',
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // Time Display - IMG_TIME Widget
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 25,
                    hour_startY: 220,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 95,
                    minute_startY: 220,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Date - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 92,
                    day_startY: 198,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weekday - IMG_WEEK Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 33,
                    y: 198,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Battery Arc - ARC_PROGRESS Widget
                let widget_103 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 130,
                    radius: 70,
                    start_angle: -90,
                    end_angle: 270,
                    color: 0x00CC88,
                    line_width: 8,
                    type: hmUI.data_type.BATTERY,
                    level: 50,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Battery Value - TEXT_IMG Widget
                let widget_104 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 215,
                    y: 118,
                    w: 50,
                    h: 25,
                    font_array: ['batt_digit_0.png', 'batt_digit_1.png', 'batt_digit_2.png', 'batt_digit_3.png', 'batt_digit_4.png', 'batt_digit_5.png', 'batt_digit_6.png', 'batt_digit_7.png', 'batt_digit_8.png', 'batt_digit_9.png'],
                    type: hmUI.data_type.BATTERY,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart Rate Value - TEXT_IMG Widget
                let widget_105 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 150,
                    y: 350,
                    w: 80,
                    h: 30,
                    font_array: ['heart_digit_0.png', 'heart_digit_1.png', 'heart_digit_2.png', 'heart_digit_3.png', 'heart_digit_4.png', 'heart_digit_5.png', 'heart_digit_6.png', 'heart_digit_7.png', 'heart_digit_8.png', 'heart_digit_9.png'],
                    type: hmUI.data_type.HEART,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Steps Value - TEXT_IMG Widget
                let widget_106 = hmUI.createWidget(hmUI.widget.TEXT_IMG, {
                    x: 300,
                    y: 350,
                    w: 80,
                    h: 30,
                    font_array: ['step_digit_0.png', 'step_digit_1.png', 'step_digit_2.png', 'step_digit_3.png', 'step_digit_4.png', 'step_digit_5.png', 'step_digit_6.png', 'step_digit_7.png', 'step_digit_8.png', 'step_digit_9.png'],
                    type: hmUI.data_type.STEP,
                    h_space: 1,
                    align_h: hmUI.align.CENTER_H,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Activity Arc - ARC_PROGRESS Widget
                let widget_107 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 380,
                    radius: 50,
                    start_angle: -120,
                    end_angle: 120,
                    color: 0xFF6B6B,
                    line_width: 6,
                    type: hmUI.data_type.STEP,
                    level: 50,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Bluetooth Status - IMG_STATUS Widget
                let widget_108 = hmUI.createWidget(hmUI.widget.IMG_STATUS, {
                    x: 225,
                    y: 420,
                    src: 'bluetooth_30x30.png',
                    type: hmUI.system_status.DISCONNECT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // City Name - TEXT Widget
                let widget_109 = hmUI.createWidget(hmUI.widget.TEXT, {
                    x: 170,
                    y: 445,
                    w: 140,
                    h: 25,
                    text_size: 18,
                    char_space: 0,
                    color: 0xCCCCCCFF,
                    line_space: 0,
                    align_v: hmUI.align.CENTER_V,
                    text_style: hmUI.text_style.ELLIPSIS,
                    align_h: hmUI.align.CENTER_H,
                    text: '',
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}