// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Flat structure, device-native widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Background image - Fill entire screen at native resolution
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });


                // Hour Hand
                let widget_6 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 220,
                    y: 100,
                    w: 40,
                    h: 140,
                    src: 'hour_hand.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Minute Hand
                let widget_7 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 230,
                    y: 60,
                    w: 20,
                    h: 180,
                    src: 'minute_hand.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Second Hand
                let widget_8 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 235,
                    y: 50,
                    w: 10,
                    h: 190,
                    src: 'second_hand.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Indicator
                let widget_9 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 200,
                    y: 400,
                    w: 80,
                    h: 20,
                    src: 'battery_icon.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date Display
                let widget_10 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 210,
                    y: 280,
                    w: 60,
                    h: 24,
                    src: 'date_display.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });

                // Widget delegate for lifecycle management
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        logger.log('watchface resumed');
                    },
                    pause_call() {
                        logger.log('watchface paused');
                    }
                });
            },
            onInit() {
                logger.log('Watchface initialized');
            },
            build() {
                this.init_view();
                logger.log('Watchface built and displayed');
            },
            onDestroy() {
                logger.log('Watchface destroyed, cleaning up');
            }
        });
    })();
} catch (e) {
    console.log('Watchface Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
}