// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Flat structure, device-native widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Background image - Fill entire screen at native resolution
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });


                // Time Display
                let widget_6 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 25,
                    y: 220,
                    w: 150,
                    h: 60,
                    src: 'chars_332F8A64_000.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday
                let widget_7 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 33,
                    y: 198,
                    w: 20,
                    h: 30,
                    src: 'chars_7FACE2F4_000.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date
                let widget_8 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 92,
                    y: 198,
                    w: 40,
                    h: 30,
                    src: 'chars_1AF2A253_000.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery
                let widget_9 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 189,
                    y: 98,
                    w: 33,
                    h: 57,
                    src: 'batt_1_33x57_h135s21b101.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Rate
                let widget_10 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 225,
                    y: 176,
                    w: 20,
                    h: 20,
                    src: 'heart_4_20x20_h108s16b123.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Steps
                let widget_11 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 241,
                    y: 223,
                    w: 29,
                    h: 30,
                    src: 'step_12_29x30.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Activity Arc
                let widget_12 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 226,
                    y: 280,
                    w: 25,
                    h: 25,
                    src: 'arc_25x25_h114s26b120.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });

                // Widget delegate for lifecycle management
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        logger.log('watchface resumed');
                    },
                    pause_call() {
                        logger.log('watchface paused');
                    }
                });
            },
            onInit() {
                logger.log('Watchface initialized');
            },
            build() {
                this.init_view();
                logger.log('Watchface built and displayed');
            },
            onDestroy() {
                logger.log('Watchface destroyed, cleaning up');
            }
        });
    })();
} catch (e) {
    console.log('Watchface Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
}