// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // Time Display - IMG_TIME Widget
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 25,
                    hour_startY: 220,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 95,
                    minute_startY: 220,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 92,
                    day_startY: 198,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday - IMG_WEEK Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 33,
                    y: 198,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery
                let widget_5 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 189,
                    y: 98,
                    w: 33,
                    h: 57,
                    src: 'batt_1_33x57_h135s21b101.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Heart Rate
                let widget_6 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 225,
                    y: 176,
                    w: 20,
                    h: 20,
                    src: 'heart_4_20x20_h108s16b123.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Steps
                let widget_7 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 241,
                    y: 223,
                    w: 29,
                    h: 30,
                    src: 'step_12_29x30.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Activity Arc
                let widget_8 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 226,
                    y: 280,
                    w: 25,
                    h: 25,
                    src: 'arc_25x25_h114s26b120.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // Time Display - IMG_TIME Widget
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 25,
                    hour_startY: 220,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 95,
                    minute_startY: 220,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Date - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 92,
                    day_startY: 198,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weekday - IMG_WEEK Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 33,
                    y: 198,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Battery
                let widget_103 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 189,
                    y: 98,
                    w: 33,
                    h: 57,
                    src: 'batt_1_33x57_h135s21b101.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Heart Rate
                let widget_104 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 225,
                    y: 176,
                    w: 20,
                    h: 20,
                    src: 'heart_4_20x20_h108s16b123.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Steps
                let widget_105 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 241,
                    y: 223,
                    w: 29,
                    h: 30,
                    src: 'step_12_29x30.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Activity Arc
                let widget_106 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 226,
                    y: 280,
                    w: 25,
                    h: 25,
                    src: 'arc_25x25_h114s26b120.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        logger.log('watchface resumed');
                    },
                    pause_call() {
                        logger.log('watchface paused');
                    }
                });
            },
            onInit() {
                logger.log('Watchface initialized');
            },
            build() {
                this.init_view();
                logger.log('Watchface built and displayed');
            },
            onDestroy() {
                logger.log('Watchface destroyed, cleaning up');
            }
        });
    })();
} catch (e) {
    console.log('Watchface Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
}