// Zepp OS Watchface generated by AI WatchFace Creator
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Background image - Fill entire screen
                hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(0),
                    y: px(0),
                    w: px(480),
                    h: px(480),
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // Widgets

                // Hour Hand - Time Pointer
                hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour: {
                        centerX: px(240),
                        centerY: px(170),
                        posX: px(220),
                        posY: px(100),
                        path: 'hour_hand.png',
                    },
                });
                // Minute Hand - Time Pointer
                hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour: {
                        centerX: px(240),
                        centerY: px(150),
                        posX: px(230),
                        posY: px(60),
                        path: 'minute_hand.png',
                    },
                });
                // Second Hand - Time Pointer
                hmUI.createWidget(hmUI.widget.TIME_POINTER, {
                    hour: {
                        centerX: px(240),
                        centerY: px(145),
                        posX: px(235),
                        posY: px(50),
                        path: 'second_hand.png',
                    },
                });
                // Battery Indicator - Level Indicator
                hmUI.createWidget(hmUI.widget.ARC, {
                    x: px(200),
                    y: px(400),
                    w: px(80),
                    h: px(20),
                    start_angle: 0,
                    end_angle: 360,
                    color: 0x00FF00,
                    type: hmUI.data_type.BATTERY,
                });
                // Date Display
                hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(210),
                    y: px(280),
                    w: px(60),
                    h: px(24),
                    color: 0xFFFFFFFF,
                    text_size: px(20),
                    text: '',
                    type: hmUI.data_type.DATE,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // Widget delegate for lifecycle management
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        logger.log('resume_call()');
                    },
                    pause_call() {
                        logger.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('Watchface initialized');
            },
            build() {
                this.init_view();
                logger.log('Watchface built');
            },
            onDestroy() {
                logger.log('Watchface destroyed');
            }
        });
    })();
} catch (e) {
    console.log('Watchface Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
}