// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                // Digital Time 3 - IMG_TIME Widget
                let widget_2 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 90,
                    hour_startY: 165,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 160,
                    minute_startY: 165,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date 5 - IMG_DATE Widget
                let widget_3 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 175,
                    day_startY: 43,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Month 6 - IMG_DATE Month Widget
                let widget_4 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    month_startX: 245,
                    month_startY: 43,
                    month_sc_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_tc_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_en_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_zero: 0,
                    month_space: 0,
                    month_is_character: true,
                    month_align: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Weekday 4 - IMG_WEEK Widget
                let widget_5 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 120,
                    y: 52,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_sc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_tc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Arc battery 0 - ARC_PROGRESS Widget
                let widget_6 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 200,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0x00CC88,
                    line_width: 12,
                    type: hmUI.data_type.BATTERY,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Arc steps 1 - ARC_PROGRESS Widget
                let widget_7 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 170,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0xFFD93D,
                    line_width: 12,
                    type: hmUI.data_type.STEP,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Arc heart_rate 2 - ARC_PROGRESS Widget
                let widget_8 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 140,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0xFF6B6B,
                    line_width: 12,
                    type: hmUI.data_type.HEART,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Level weather 8 - IMG_LEVEL Widget
                let widget_9 = hmUI.createWidget(hmUI.widget.IMG_LEVEL, {
                    x: 350,
                    y: 210,
                    image_array: ["weather_0.png", "weather_1.png", "weather_2.png", "weather_3.png", "weather_4.png", "weather_5.png", "weather_6.png", "weather_7.png", "weather_8.png", "weather_9.png", "weather_10.png", "weather_11.png", "weather_12.png", "weather_13.png", "weather_14.png", "weather_15.png", "weather_16.png", "weather_17.png", "weather_18.png", "weather_19.png", "weather_20.png", "weather_21.png", "weather_22.png", "weather_23.png", "weather_24.png", "weather_25.png", "weather_26.png", "weather_27.png", "weather_28.png"],
                    image_length: 29,
                    type: hmUI.data_type.WEATHER_CURRENT,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========

                // Digital Time 3 - IMG_TIME Widget
                let widget_100 = hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: 90,
                    hour_startY: 165,
                    hour_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    hour_space: 0,
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: 160,
                    minute_startY: 165,
                    minute_array: ['time_digit_0.png', 'time_digit_1.png', 'time_digit_2.png', 'time_digit_3.png', 'time_digit_4.png', 'time_digit_5.png', 'time_digit_6.png', 'time_digit_7.png', 'time_digit_8.png', 'time_digit_9.png'],
                    minute_space: 0,
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Date 5 - IMG_DATE Widget
                let widget_101 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    day_startX: 175,
                    day_startY: 43,
                    day_sc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_tc_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_en_array: ['date_digit_0.png', 'date_digit_1.png', 'date_digit_2.png', 'date_digit_3.png', 'date_digit_4.png', 'date_digit_5.png', 'date_digit_6.png', 'date_digit_7.png', 'date_digit_8.png', 'date_digit_9.png'],
                    day_zero: 1,
                    day_space: 0,
                    day_align: hmUI.align.LEFT,
                    day_is_character: false,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Month 6 - IMG_DATE Month Widget
                let widget_102 = hmUI.createWidget(hmUI.widget.IMG_DATE, {
                    month_startX: 245,
                    month_startY: 43,
                    month_sc_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_tc_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_en_array: ['month_0.png', 'month_1.png', 'month_2.png', 'month_3.png', 'month_4.png', 'month_5.png', 'month_6.png', 'month_7.png', 'month_8.png', 'month_9.png', 'month_10.png', 'month_11.png'],
                    month_zero: 0,
                    month_space: 0,
                    month_is_character: true,
                    month_align: hmUI.align.LEFT,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Weekday 4 - IMG_WEEK Widget
                let widget_103 = hmUI.createWidget(hmUI.widget.IMG_WEEK, {
                    x: 120,
                    y: 52,
                    week_en: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_sc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    week_tc: ['week_0.png', 'week_1.png', 'week_2.png', 'week_3.png', 'week_4.png', 'week_5.png', 'week_6.png'],
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Arc battery 0 - ARC_PROGRESS Widget
                let widget_104 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 200,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0x00CC88,
                    line_width: 12,
                    type: hmUI.data_type.BATTERY,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Arc steps 1 - ARC_PROGRESS Widget
                let widget_105 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 170,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0xFFD93D,
                    line_width: 12,
                    type: hmUI.data_type.STEP,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Arc heart_rate 2 - ARC_PROGRESS Widget
                let widget_106 = hmUI.createWidget(hmUI.widget.ARC_PROGRESS, {
                    center_x: 240,
                    center_y: 240,
                    radius: 140,
                    start_angle: 135,
                    end_angle: 405,
                    color: 0xFF6B6B,
                    line_width: 12,
                    type: hmUI.data_type.HEART,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                // Level weather 8 - IMG_LEVEL Widget
                let widget_107 = hmUI.createWidget(hmUI.widget.IMG_LEVEL, {
                    x: 350,
                    y: 210,
                    image_array: ["weather_0.png", "weather_1.png", "weather_2.png", "weather_3.png", "weather_4.png", "weather_5.png", "weather_6.png", "weather_7.png", "weather_8.png", "weather_9.png", "weather_10.png", "weather_11.png", "weather_12.png", "weather_13.png", "weather_14.png", "weather_15.png", "weather_16.png", "weather_17.png", "weather_18.png", "weather_19.png", "weather_20.png", "weather_21.png", "weather_22.png", "weather_23.png", "weather_24.png", "weather_25.png", "weather_26.png", "weather_27.png", "weather_28.png"],
                    image_length: 29,
                    type: hmUI.data_type.WEATHER_CURRENT,
                    show_level: hmUI.show_level.ONLY_AOD
                });

                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}