// Zepp OS Watchface generated by AI WatchFace Creator (V2 Format)
// V2 Manifest: Full A OD support with dynamic widgets
// Compatible with Amazfit Balance 2, Balance, Active Max
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');
        
        // Sensor for weather and system info
        let weatherSensor = null;

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Initialize sensors
                try {
                    weatherSensor = hmSensor.createSensor(hmSensor.id.WEATHER);
                } catch (e) {
                    logger.log('Weather sensor init failed:', e);
                }
                
                // ========== NORMAL MODE BACKGROUND ==========
                let widget_1 = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // ========== NORMAL MODE WIDGETS ==========

                
                // ========== AOD MODE BACKGROUND ==========
                let widget_aod_bg = hmUI.createWidget(hmUI.widget.IMG, {
                    x: 0,
                    y: 0,
                    w: 480,
                    h: 480,
                    src: 'background.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_AOD
                });
                
                // ========== AOD MODE WIDGETS ==========


                // Widget delegate for lifecycle management (matches working reference)
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        console.log('resume_call()');
                        let tipoSchermo = hmSetting.getScreenType();
                        if (tipoSchermo === hmSetting.screen_type.WATCHFACE) {
                            // NORMAL MODE updates
                        } else if (tipoSchermo === hmSetting.screen_type.AOD) {
                            // AOD MODE updates
                        }
                    },
                    pause_call() {
                        console.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('index page.js on init invoke');
            },
            build() {
                this.init_view();
                logger.log('index page.js on ready invoke');
            },
            onDestroy() {
                logger.log('index page.js on destroy invoke');
            }
        });
        ;
    })();
} catch (e) {
    console.log('Mini Program Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
    ;
}