// Zepp OS Watchface generated by AI WatchFace Creator
try {
    (() => {
        const __$$app$$__ = __$$hmAppManager$$__.currentApp;
        function getApp() {
            return __$$app$$__.app;
        }
        function getCurrentPage() {
            return __$$app$$__.current && __$$app$$__.current.module;
        }
        const __$$module$$__ = __$$app$$__.current;
        const h = new DeviceRuntimeCore.WidgetFactory(new DeviceRuntimeCore.HmDomApi(__$$app$$__, __$$module$$__));
        const {px} = __$$app$$__.__globals__;
        const logger = Logger.getLogger('WatchFaceEditor');

        __$$module$$__.module = DeviceRuntimeCore.WatchFace({
            init_view() {
                // Background image - Fill entire screen
                hmUI.createWidget(hmUI.widget.IMG, {
                    x: px(0),
                    y: px(0),
                    w: px(480),
                    h: px(480),
                    src: 'bg.png',
                    alpha: 255,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // Widgets

                // Hour Hand - Time Display (IMG_TIME)
                hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: px(220),
                    hour_startY: px(100),
                    hour_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: px(270),
                    minute_startY: px(100),
                    minute_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Minute Hand - Time Display (IMG_TIME)
                hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: px(230),
                    hour_startY: px(60),
                    hour_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: px(280),
                    minute_startY: px(60),
                    minute_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Second Hand - Time Display (IMG_TIME)
                hmUI.createWidget(hmUI.widget.IMG_TIME, {
                    hour_zero: 1,
                    hour_startX: px(235),
                    hour_startY: px(50),
                    hour_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    hour_align: hmUI.align.LEFT,
                    minute_zero: 1,
                    minute_startX: px(285),
                    minute_startY: px(50),
                    minute_array: ['chars_time_digit_0.png','chars_time_digit_1.png','chars_time_digit_2.png','chars_time_digit_3.png','chars_time_digit_4.png','chars_time_digit_5.png','chars_time_digit_6.png','chars_time_digit_7.png','chars_time_digit_8.png','chars_time_digit_9.png'],
                    minute_align: hmUI.align.LEFT,
                    minute_follow: 0,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Battery Indicator
                hmUI.createWidget(hmUI.widget.IMG_LEVEL, {
                    x: px(200),
                    y: px(400),
                    image_array: ['level_0.png', 'level_1.png', 'level_2.png', 'level_3.png', 'level_4.png'],
                    image_length: 5,
                    type: hmUI.data_type.BATTERY,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                // Date Display
                hmUI.createWidget(hmUI.widget.TEXT, {
                    x: px(210),
                    y: px(280),
                    w: px(60),
                    h: px(24),
                    color: 0xFFFFFFFF,
                    text_size: px(20),
                    text: '',
                    type: hmUI.data_type.DATE,
                    show_level: hmUI.show_level.ONLY_NORMAL
                });
                
                // Widget delegate for lifecycle management
                const widgetDelegate = hmUI.createWidget(hmUI.widget.WIDGET_DELEGATE, {
                    resume_call() {
                        logger.log('resume_call()');
                    },
                    pause_call() {
                        logger.log('pause_call()');
                    }
                });
            },
            onInit() {
                logger.log('Watchface initialized');
            },
            build() {
                this.init_view();
                logger.log('Watchface built');
            },
            onDestroy() {
                logger.log('Watchface destroyed');
            }
        });
    })();
} catch (e) {
    console.log('Watchface Error', e);
    e && e.stack && e.stack.split(/\n/).forEach(i => console.log('error stack', i));
}